---
title: "CV"
---


## Short bio

Currently I am working as postdoctoral in oceanography. I have a PhD statistics by UFRJ Brazilian university and posdoctoral in ecological modelling by UFRJ Brazilian university Institute of Biology. My interest is based on developing Bayesian statistical tools to applied real problems.


## Education
- Posdoctoral in ecological modelling, [The Federal University of Rio de Janeiro / Ecologia Biologia](http://www.ppgecologia.biologia.ufrj.br/), Brazil, 2020. <BR> Under supervision of [Prof Rodrigo Moura](http://lattes.cnpq.br/8814217649491828). 
- PhD in statistics, [The Federal University of Rio de Janeiro / DME ](http://www.dme.ufrj.br/), Brazil, 2018. <BR> Under supervision of [Prof Helio Migon](http://lattes.cnpq.br/7997248190492823). ([Thesis](http://www.pg.im.ufrj.br/teses/Estatistica/Doutorado/040.pdf))
- Master in statistics, [The Federal University of Rio de Janeiro / DME ](http://www.dme.ufrj.br/), Brazil, 2014. <BR> Under supervision of [Prof Fernando Moura](http://lattes.cnpq.br/7139199699142105). ([Thesis](http://www.pg.im.ufrj.br/teses/Estatistica/Mestrado/144.pdf))

## Students

  - Mariana Soares (2019-2020) Statistics/ Institute of Matematics.
  - Larissa Maracajá (2019-2020) Statistics/ Institute of Matematics.

